mystr="this is python"
#print(mystr)
#print(mystr.strip())
#print(mystr.lower())
#print(mystr.upper())
#print(mystr.replace("This","That"))
#print(mystr.split(","))
#print(mystr.capitalize())
#print(mystr.casefold())
#print(mystr.count("t"))
#print(mystr.endswith("."))
#print(mystr.find("i"))
#print(mystr.index("Python"))
#print(mystr.isalnum())
#print(mystr.isalpha())
#print(mystr.isdigit())
print(mystr.title())